### ISSUE TITLE
Missing method_name inside reflex

### ISSUE THREAD

**Issue by ksweetie** [podia/stimulus_reflex_testing#5]
Hey all,

First off, a huge thank you for putting this repo together! I was so relieved when I found it, and it works great!

One thing that would be helpful for me is if `method_name` were available inside a reflex. In SR proper, this gets set [here](https://github.com/hopsoft/stimulus_reflex/blob/master/lib/stimulus_reflex/channel.rb#L44):

I'm not sure of the best way to add this, because currently, the test reflexes are formed in two steps. The _easy_ fix would be to add method name to the opts and set it [here](https://github.com/podia/stimulus_reflex_testing/blob/main/lib/stimulus_reflex/test_case.rb#L27). However, that would require duplicating the method name in practice, ie:

```rb
reflex = build_reflex(url: "foo", method_name: "create")
reflex.run(:create)
```

That would get the job done, but it would be nice to not have to set it during `build_reflex` and repeat it later. Any ideas?

**Comment by ksweetie** [comment]
@jasoncharnes any thoughts on this? I'm happy to help out with a PR, but curious what direction you think we should go, if at all. Thank you!

**Comment by jasoncharnes** [comment]
@ksweetie I'm very sorry for the delay, thank you for the nudge.

For now, I think having `method_name` as an optional argument to `build_reflex` would work. However, I strongly agree with you here: 

> That would get the job done, but it would be nice to not have to set it during build_reflex and repeat it later. Any ideas?

I don't have any _quick_ ideas off the top of my head. I'd gladly accept a PR with `method_name` and we can work to improve this over time.
