### ISSUE TITLE
Needs update for SR 3.4

### ISSUE THREAD

**Issue by rrosen** [podia/stimulus_reflex_testing#6]
stimulus_reflex_testing won't load when the app is using the pre-releases of StimulusReflex 3.4.  I get this error when rspec is setting up:

```
  uninitialized constant StimulusReflex::Channel
```

As of at least StimulusReflex 3.4.0-pre8, ~~this class no longer exists, and I don't see an obvious replacement.~~

EDIT

SR still defines `StimulusReflex::Channel` it is but not available during bundler setup.

**Comment by rrosen** [comment]
Turns out SR still defines StimulusReflex::Channel it is but not available during bundler setup.

If I change my Gemfile to 

```
gem "stimulus_reflex_testing"
```

and `require "stimulus_reflex_testing` in `spec/rails_helper.rb` I can get past the missing constant error.  Then I get this error:

```
       undefined method `stream_name' for #<StimulusReflex::TestCase::TestChannel:0x00007f815c05b498>
```

stream_name is defined on `StimulusReflex::Channel`  Is there an instance the TestChannel could delegate to?

**Comment by marcoroth** [comment]
See: https://github.com/hopsoft/stimulus_reflex/pull/346

**Comment by existentialmutt** [comment]
I've got this figured out on my box.  StimulusReflex::TestCase::TestChannel needs a few methods added to make it quack like StimulusReflex::Channel.  Will send a PR next chance I get.

**Comment by ksweetie** [comment]
I'm seeing an error when using https://github.com/podia/stimulus_reflex_testing/pull/7. After adding `require: false` to the Gemfile as mentioned, I get this:

```
Failure/Error: require "stimulus_reflex_testing/rspec"

NameError:
  uninitialized constant StimulusReflex::TestCase
# ./spec/rails_helper.rb:23:in `<top (required)>'
```

I'm on Rails 5.2, maybe that has something to do with it?

**Comment by existentialmutt** [comment]
@ksweetie try this in rails_helper.rb:

```
require "stimulus_reflex_testing"
require "stimulus_reflex_testing/rspec"
```

**Comment by ksweetie** [comment]
@existentialmutt that did the trick, thank you so much!
